# This is a basic workflow to help you get started with Actions

name: Sprightly Package Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - name: Fetch all git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      
      # Install node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org/'
      
      # NPM Access test
      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      
      - name: Test NPM login
        run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Install dependencies
      - name: Install
        run: yarn install

      # Login to GIT
      - name: Git Identity
        run: |
          git config --global user.name 'shaunoff'
          git config --global user.email 'shaunoff@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lerna Build
        run: yarn build

      # Runs a single command using the runners shell
      - name: Publish Packages to NPM
        run: yarn publish-packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}